# Generated by Django 3.0.6 on 2022-08-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0003_auto_20220804_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='merge_ratings_book_datasets',
            new_name='merge_ratings_books_datasets',
        ),
    ]
